### ISSUE TITLE
FaceRecognition.java: cannot find symbol cvMat.maskedType()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [boybeak/javacv#229]
```
What steps will reproduce the problem?
--------------------------------------
Just try to compile samples/FaceRecognition.java

What is the expected output? What do you see instead?
-----------------------------------------------------
FaceRecognition.java:755: error: cannot find symbol
    final int type = cvMat.maskedType();
                          ^
  symbol:   method maskedType()
  location: variable cvMat of type CvMat

What version of the product are you using? On what operating system?
--------------------------------------------------------------------
JavaCV 0.2 on Ubuntu 12.04

Please provide any additional information below.
------------------------------------------------
The sample worked fine on JavaCV 0.1

Thanks, and keep up your good work!
```

Original issue reported on code.google.com by `alceste....@unica.it` on 2 Aug 2012 at 2:57
